openapi: 3.0.0
info:
  title: Npcf_MBSPolicyControl API
  version: 1.0.0-alpha.1
  description: |
    MBS Session Policy Control Service
    © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).
    All rights reserved.

externalDocs:
  description: 3GPP TS 29.537 V0.1.0; 5G System; Multicast/Broadcast Policy Control Services.
  url: 'http://www.3gpp.org/ftp/Specs/archive/29_series/29.537/'

security:
  - {}
  - oAuth2ClientCredentials:
    - npcf-mbspolicycontrol

servers:
  - url: '{apiRoot}/npcf-mbspolicycontrol/v1'
    variables:
      apiRoot:
        default: https://example.com
        description: apiRoot as defined in subclause 4.4 of 3GPP TS 29.501.

paths:
  /mbs-policies:
    post:
      summary: Request the creation of a new Individual MBS Policy resource.
      operationId: CreateMBSPolicy
      tags:
        - MBS Policies (Collection)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MbsPolicyCtxtData'
      responses:
        '201':
          description: Created. An Individual MBS Policy resource is successfully created and a representation of the created resource is returned. 
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MbsPolicyData'
          headers:
            Location:
              description: Contains the URI of the newly created Individual MBS Policy resource.
              required: true
              schema:
                type: string
        '400':
          $ref: 'TS29571_CommonData.yaml#/components/responses/400'
        '401':
          $ref: 'TS29571_CommonData.yaml#/components/responses/401'
        '403':
          $ref: 'TS29571_CommonData.yaml#/components/responses/403'
        '404':
          description: Not Found
        '411':
          $ref: 'TS29571_CommonData.yaml#/components/responses/411'
        '413':
          $ref: 'TS29571_CommonData.yaml#/components/responses/413'
        '415':
          $ref: 'TS29571_CommonData.yaml#/components/responses/415'
        '429':
          $ref: 'TS29571_CommonData.yaml#/components/responses/429'
        '500':
          $ref: 'TS29571_CommonData.yaml#/components/responses/500'
        '503':
          $ref: 'TS29571_CommonData.yaml#/components/responses/503'
        default:
          $ref: 'TS29571_CommonData.yaml#/components/responses/default'
      callbacks:
        MbsPolicyUpdateNotification:
          '{$request.body#/notificationUri}/update': 
            post:
              requestBody:
                required: true
                content:
                  application/json:
                    schema:
                      $ref: '#/components/schemas/MbsPolicyNotif'
              responses:
                '204':
                  description: No Content. The MBS Policy Update Notification was successfully received.
                '307':
                  $ref: 'TS29571_CommonData.yaml#/components/responses/307'
                '308':
                  $ref: 'TS29571_CommonData.yaml#/components/responses/308'
                '401':
                  $ref: 'TS29571_CommonData.yaml#/components/responses/401'
                '403':
                  $ref: 'TS29571_CommonData.yaml#/components/responses/403'
                '404':
                  $ref: 'TS29571_CommonData.yaml#/components/responses/404'
                '411':
                  $ref: 'TS29571_CommonData.yaml#/components/responses/411'
                '413':
                  $ref: 'TS29571_CommonData.yaml#/components/responses/413'
                '415':
                  $ref: 'TS29571_CommonData.yaml#/components/responses/415'
                '429':
                  $ref: 'TS29571_CommonData.yaml#/components/responses/429'
                '500':
                  $ref: 'TS29571_CommonData.yaml#/components/responses/500'
                '503':
                  $ref: 'TS29571_CommonData.yaml#/components/responses/503'
                default:
                  $ref: 'TS29571_CommonData.yaml#/components/responses/default'

  /mbs-policies/{mbsPolicyId}:
    get:
      summary: Read an Individual MBS Policy.
      operationId: GetMBSPolicy
      tags:
        - Individual MBS Policy (Document)
      parameters:
        - name: mbsPolicyId
          in: path
          description: Contains the identifier of the concerned Individual MBS Session Policy Association.
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK. The requested Individual MBS Policy resource is successfully returned.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MbsPolicyData'
        '307':
          $ref: 'TS29571_CommonData.yaml#/components/responses/307'
        '308':
          $ref: 'TS29571_CommonData.yaml#/components/responses/308'
        '400':
          $ref: 'TS29571_CommonData.yaml#/components/responses/400'
        '401':
          $ref: 'TS29571_CommonData.yaml#/components/responses/401'
        '403':
          $ref: 'TS29571_CommonData.yaml#/components/responses/403'
        '404':
          $ref: 'TS29571_CommonData.yaml#/components/responses/404'
        '406':
          $ref: 'TS29571_CommonData.yaml#/components/responses/406'
        '429':
          $ref: 'TS29571_CommonData.yaml#/components/responses/429'
        '500':
          $ref: 'TS29571_CommonData.yaml#/components/responses/500'
        '503':
          $ref: 'TS29571_CommonData.yaml#/components/responses/503'
        default:
          $ref: 'TS29571_CommonData.yaml#/components/responses/default'

components:
  securitySchemes:
    oAuth2ClientCredentials:
      type: oauth2
      flows: 
        clientCredentials: 
          tokenUrl: '{nrfApiRoot}/oauth2/token'
          scopes:
            npcf-mbspolicycontrol: Access to the Npcf_MBSPolicyControl API

  schemas:
    MbsPolicyCtxtData:
      description: Contains the parameters used to request the creation of an Individual MBS Policy resource.
      type: object
      properties:
        mbsSessionId:
          $ref: 'TS29571_CommonData.yaml#/components/schemas/MbsSessionId'
        dnn:
          $ref: 'TS29571_CommonData.yaml#/components/schemas/Dnn'
        snssai:
          $ref: 'TS29571_CommonData.yaml#/components/schemas/Snssai'
        notificationUri:
          $ref: 'TS29571_CommonData.yaml#/components/schemas/Uri'
        suppFeat:
          $ref: 'TS29571_CommonData.yaml#/components/schemas/SupportedFeatures'
      required:
        - mbsSessionId
        - dnn
        - snssai
        - notificationUri

    MbsPolicyData:
      description: Contains the MBS policy data of an Individual MBS Policy resource.
      type: object
      properties:
        mbsPolicyCtxtData:
          $ref: '#/components/schemas/MbsPolicyCtxtData'
        suppFeat:
          $ref: 'TS29571_CommonData.yaml#/components/schemas/SupportedFeatures'
      required:
        - mbsPolicyCtxtData

    MbsPolicyNotif:
      description: Represents an MBS Policy Update Notification.
      type: object
      properties:
        mbsSessionId:
          $ref: 'TS29571_CommonData.yaml#/components/schemas/MbsSessionId'
      required:
        - mbsSessionId
